[package]
name = "neptune"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
rand = "0.8.5"
chrono = "0.4.19"
walkdir = "2.3.2"
hotwatch = "0.4.6"
fs_extra = "1.2.0"
serialport = "4.2.0"
libadwaita = "0.1.1"
run_script = "0.9.0"
lazy_static = "1.4.0"
pretty_env_logger = "0.4.0"
clap = { version = "3.1.18", features = ["derive"] }
figment = { version = "0.10.6", features = ["toml"] }
serde = { version = "1.0.137", features = ["derive"] }
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread", "sync"] }
