[package]
name = "neptune"
version = "0.1.0"
authors = ["Yummiii <Leeo05050@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enigo = "0.0.14"
umiko = "0.1.2"
passwords = "3.1.7"
clipboard = "0.5.0"
uuid = { version = "0.8.2", features = ["v4"] }
windows-service = "0.3.1"