[package]
name = "neptune"
version = "0.1.0"
authors = ["yummi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
tokio = { version = "1.6.0", features = ["fs", "macros", "rt-multi-thread"] }
glob = "0.3.0"