[package]
name = "neptune"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libadwaita = "0.1.1"
clap = { version = "3.1.18", features = ["derive"] }
figment = { version = "0.10.6", features = ["toml"] }
serde = { version = "1.0.137", features = ["derive"] }
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread", "sync"] }
