[package]
name = "neptune"
version = "0.1.0"
authors = ["yummi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#tokio = { version = "1.6.0", features = ["fs", "macros", "rt-multi-thread"] }
serde = { version = "1.0", features = ["derive"] }
confy = "0.4.0"
clap = "^3.0.0-beta.2"
passwords = "3.1.7"
uuid = { version = "0.8.2", features = ["v4"] }