[package]
name = "neptune"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
daemonize="0.4.1"
hotwatch="0.4.6"
run_script = "0.9.0"
fs_extra = "1.2.0"