[package]
name = "neptune"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
hotwatch="0.4.6"
run_script = "0.9.0"
fs_extra = "1.2.0"
xdg-user = "0.2.1"
serialport = "4.1.0"
tokio = {version = "1.17.0", features = ["macros", "rt-multi-thread", "sync"]}
lazy_static="1.4.0"

[build-dependencies]
pkg-config = "0.3.25"
cc = "1.0.73"