[screenlock]
enabled = true
images = [

]
images_dirs = [
    "/home/yummi/Okayu/hum/b/"
]
grab_input = true

[screenshots]
enabled = true
initial_check = true
screenshots_watch_dir = "/home/yummi/.xdg/pictures/Capturas de tela/"
screenshots_target_dir = "/home/yummi/Okayu/Printis/%Y-%m/"

[interactions.serial_port]
enabled = true
rate = 9600
path = "/dev/ttyUSB0"

[interactions.websocket]
enabled = true
bind_addr = "0.0.0.0:3012"