[screenlock]
enabled = true
images = [
    ""
]
grab_input = true

[interactions.serial_port]
enabled = true
rate = 9600
path = "/dev/ttyUSB0"

[interactions.websocket]
enabled = true
bind_addr = "0.0.0.0:3012"
